# Font
font_family			CommitMono Nerd Font
bold_font			Auto
italic_font			Auto
bold_italic_font	Auto
font_size			14.0

# Transparency
background_opacity 0.6

# Padding
window_padding_width 1

# Theme
include Kaolin Ocean.conf
