# These settings were set by the catalyst build script that automatically
# built this stage.
# Please consult /usr/share/portage/config/make.conf.example for a more
# detailed example.
COMMON_FLAGS="-march=native -O2 -pipe"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"
CGO_CFLAGS="${COMMON_FLAGS}"
CGO_CXXFLAGS="${COMMON_FLAGS}"
CGO_FFLAGS="${COMMON_FLAGS}"
RUSTFLAGS="-C target-cpu=native"

PORTAGE_NICENESS=1
MAKEOPTS="-j8 -l9"
EMERGE_DEFAULT_OPTS="--jobs=8 --load-average=9"
ACCEPT_LICENSE="*"
ACCEPT_KEYWORDS="~amd64"

USE="-systemd -flatpak -wayland -gnome -kde -consolekit -cups \
    dist-kernel modules-sign networkmanager dbus elogind"

# NOTE: This stage was built with the bindist USE flag enabled
PORTDIR="/var/db/repos/gentoo"
DISTDIR="/var/cache/distfiles"
PKGDIR="/var/cache/binpkgs"

# This sets the language of build output to English.
# Please keep this setting intact when reporting bugs.
LC_MESSAGES=C.utf8

GRUB_PLATFORMS="efi-64"

GENTOO_MIRRORS="https://mirrors.ircam.fr/pub/gentoo-distfiles/ \
    rsync://mirrors.ircam.fr/pub/gentoo-distfiles/ \
    https://mirror.eu.oneandone.net/linux/distributions/gentoo/gentoo/ \
    rsync://mirror.eu.oneandone.net/gentoo/ \
    https://mirror.dogado.de/gentoo \
    https://ftp.agdsn.de/gentoo \
    rsync://ftp.agdsn.de/gentoo \
    ftp://ftp.ntua.gr/pub/linux/gentoo/"
