# Map prefix to 'C-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Split panes using '|' and '-'
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# Switch panes using Alt + <arrow key>
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Reload config
bind r source-file ~/.config/tmux/tmux.conf \; display "Config reloaded"

# Status bar
set -g base-index 1
setw -g pane-base-index 1

set -g status-position bottom
set -g status-justify left
set -g status-style 'fg=green'

set -g status-left ''

set -g status-right-style 'fg=green'
set -g status-right '%d-%b-%y %H:%M'

setw -g window-status-current-style 'fg=black bg=green'
setw -g window-status-current-format ' #I #W #F '

setw -g window-status-style 'fg=green bg=black'
setw -g window-status-format ' #I #[fg=white]#W #[fg=green]#F '
