# Load Xresources
xrdb -merge ${XDG_CONFIG_HOME:-$HOME/.config}/x11/Xresources

gentoo-pipewire-launcher &
picom &
dwmblocks &
feh --no-fehbg --bg-fill ~/.local/share/Wallpapers/styljor.jpg &

exec dbus-launch --sh-syntax --exit-with-session dwm
