# Load Xresources
xrdb -merge ${XDG_CONFIG_HOME:-$HOME/.config}/x11/Xresources

gentoo-pipewire-launcher &
dwmblocks &
nm-applet &
picom &
feh --randomize --no-fehbg --bg-fill ~/.local/share/Wallpapers/* &

exec dbus-launch --sh-syntax --exit-with-session dwm
