backend = "glx";

blur: {
    method = "dual_kawase";
    strength = 7;
    background = true;
    background-frame = false;
    background-fixed = false;
};

blur-background-exclude = [
    "class_g = 'Brave-browser'",
    "window_type = 'dock'",
    "window_type = 'desktop'",
    "window_type = 'menu'",
    "window_type = 'dropdown_menu'",
    "window_type = 'popup_menu'",
    "window_type = 'tooltip'"
];
